services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    ports:
      - "8554:8554"
    networks: [rtsp-network]

  camera-1:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-1
    command: >
      -re -stream_loop -1 -i /videos/violence_1.gif
      -vf "scale=640:360"
      -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -bf 0 -r 25
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam1
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks: [rtsp-network]

  camera-2:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-2
    command: >
      -re -stream_loop -1 -i /videos/violence_2.gif
      -vf "scale=640:360"
      -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -bf 0 -r 25
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam2
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks: [rtsp-network]

  camera-3:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-3
    command: >
      -re -stream_loop -1 -i /videos/no_violence_1.gif
      -vf "scale=640:360"
      -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -bf 0 -r 25
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam3
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks: [rtsp-network]

  camera-4:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-4
    command: >
      -re -stream_loop -1 -i /videos/violence_3.gif
      -vf "scale=640:360"
      -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -bf 0 -r 25
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam4
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks: [rtsp-network]

networks:
  rtsp-network:
    driver: bridge
