services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    ports:
      - "8554:8554"
    networks:
      - rtsp-network
      - violence-detection-network

  camera-1:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-1
    command: >
      -re -stream_loop -1 -i /videos/violence_1.mp4
      -c:v copy -c:a aac
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam1
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks:
      - rtsp-network
      - violence-detection-network

  camera-2:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-2
    command: >
      -re -stream_loop -1 -i /videos/violence_2.mp4
      -c:v copy -c:a aac
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam2
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks:
      - rtsp-network
      - violence-detection-network

  camera-3:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-3
    command: >
      -re -stream_loop -1 -i /videos/non_violence_1.mp4
      -c:v copy -c:a aac
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam3
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks:
      - rtsp-network
      - violence-detection-network

  camera-4:
    image: jrottenberg/ffmpeg:5.1-alpine
    container_name: camera-4
    command: >
      -re -stream_loop -1 -i /videos/violence_3.mp4
      -c:v copy -c:a aac
      -f rtsp -rtsp_transport tcp rtsp://rtsp-server:8554/cam4
    volumes:
      - ./test-videos:/videos
    depends_on: [rtsp-server]
    networks:
      - rtsp-network
      - violence-detection-network

networks:
  rtsp-network:
    driver: bridge
  violence-detection-network:
    external: true
